version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./temp:/app/temp
      - ./database.db:/app/database.db
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:////app/database.db
    depends_on:
      - celery-worker

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.backend.services.celery_service.celery worker --loglevel=info
    volumes:
      - ./temp:/app/temp
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"